### ISSUE TITLE
Passphrase for Private SSH Key

### ISSUE THREAD

**Issue by Naendo** [wshihadeh/docker-deployment-action#13]
Hey,
I was wondering if there is a way to include passphrases into the arguments.

**Comment by alsowayegh** [comment]
> Hey,
> I was wondering if there is a way to include passphrases into the arguments.
 did you solve this issue? cause I'm facing the same issue atm

**Comment by alsowayegh** [comment]
> Hey,
> I was wondering if there is a way to include passphrases into the arguments.

did you solve this issue? I'm currently facing it 
@Naendo
