### ISSUE TITLE
Failed with docker-compose: not found

### ISSUE THREAD

**Issue by VolkovVlad** [wshihadeh/docker-deployment-action#14]
Faced a problem that I cannot solve 😢

While the pipeline is running I get the error on deploy step.
It looks like this
![image](https://user-images.githubusercontent.com/21365832/99889315-e4170e00-2c64-11eb-87da-5cf853f9a1e6.png)

Step in the workflow:
```- name: Deploy
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ubuntu@web.closapp.space
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          pull_images_first: 'true'
          args: up -d webapp
```

Any idea why this is happening?

**Comment by wshihadeh** [comment]
you need to make sure that docker-compose. is installed on the remote server

**Comment by VolkovVlad** [comment]
I made sure docker-compose is installed. 
I created a Makefile with this inner on remote server: `cd <some internal path> && docker-compose pull webapp && docker-compose up -d --force-recreate  webapp`, then I ran a simple ssh-script wrapped it gh-action: `make webapp` 

This workaround works fine.
