### ISSUE TITLE
docker-compose, No such file or directory

### ISSUE THREAD

**Issue by RozennGZ** [wshihadeh/docker-deployment-action#16]
I am trying your "case four, Deploy a docker-compose stack to a remote Docker server by running the command on the Docker node" 

The connexion is done and OK (I can see the folder stacks which has been created in the server).
I have an error "docker-compose.yml" : No such file or directory" whereas I have checked, I used the correct name for the docker-compose file (I have .yml and not yaml as in your example). 

Please Have you an idea of this error ???? 

Registering SSH keys...
Agent pid 11
Identity added: /github/home/.ssh/id_rsa (rsa-key-20201015)
Add known hosts
Execute Over SSH: mkdir -p /home/ubuntu/test_manager/stacks || true

docker-compose.yml: No such file or directory

**Comment by wshihadeh** [comment]
can you share the workflow you defined ?

**Comment by RozennGZ** [comment]
Yes, 
name: Publish on Server host

on:
  push:
    branches:
    - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Deploy to Docker Host
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: XXX@XXXXX
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          deploy_path: /home/ubuntu/test_manager
          stack_file_name: 'docker-compose.yml'
          copy_stack_file: true
          keep_files: 5
          args: up -d
          docker_prune: 'false'
          pull_images_first: 'false'

**Comment by wshihadeh** [comment]
I checked your project and it seems that you have issues with ssh keys on the remote server 
https://github.com/RozennGZ/test_manager/runs/1840767680
```
Execute Over SSH: mkdir -p /home/ubuntu/test_manager/stacks || true
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:ZSrXE3EjdqaD+9g53YXKmYyJjP9QWbixSAmSz54qh/0.
Please contact your system administrator.
```

**Comment by RozennGZ** [comment]
Yes, I saw this issue but I though it was not the problem.
I change to remove this warning, but I have still an issue : 
"Registering SSH keys...
Agent pid 13
Identity added: /github/home/.ssh/id_rsa (rsa-key-20201015)
Add known hosts
Execute Over SSH: mkdir -p /home/ubuntu/test_manager/stacks || true
Warning: Permanently added '51.68.88.177' (ECDSA) to the list of known hosts.
docker-compose.yml: No such file or directory"

Do you think that is it still an issue with ssh keys ?

**Comment by wshihadeh** [comment]
I still can see the same warning on the last ci execution, with this warning most probably ssh connection is working as expected for some reason it seems that ssh key on the remote side changes or the ci worker has a different ssh key 
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

Please pay attention to this message 
```
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:ZSrXE3EjdqaD+9g53YXKmYyJjP9QWbixSAmSz54qh/0.
```
and here is a working example of the action : https://github.com/wshihadeh/docker-deployment-action/blob/master/.github/workflows/main.yml
