### ISSUE TITLE
Adding port parameter

### ISSUE THREAD

**Issue by elymatos** [wshihadeh/docker-deployment-action#8]
Thanks for the good job!
I need to add a port parameters as my ssh server is not running at port 22. How can I add this?

**Comment by wshihadeh** [comment]
try to do the following

```
remote_docker_host: user@myswarm.com:456
```

**Comment by niktob560** [comment]
I have an error ``stderr=Host key verification failed.``
How can I fix tis?
Keys are exported

**Comment by wshihadeh** [comment]
It seems that the ssh keys you provided are the wrong ones

**Comment by r3cha** [comment]
@wshihadeh Thanks a lot for this action
@elymatos You can try  `r3cha/docker-deployment-action@add-ssh-port` now I’m testing it 
Here is PR https://github.com/wshihadeh/docker-deployment-action/pull/11 to the @wshihadeh repo

**Comment by r3cha** [comment]
@elymatos tested works well

**Comment by r3cha** [comment]
@niktob560  Your error happens because under hood action uses ssh & scp and they can’t accept port as host:port
You can use r3cha/docker-deployment-action@master action temporary or wait infill it will be merged
