### ISSUE TITLE
Invalid ssh key format 

### ISSUE THREAD

**Issue by dAverk** [wshihadeh/docker-deployment-action#9]
Hey guys!
I have similar issue like #1  - and get same error. But same key works with fifsky/ssh-action@master without any problems, can you specify key format?

**Comment by dAverk** [comment]
Found possbile fix - converted key to RSA format and all ok, I think better add this to README

**Comment by wshihadeh** [comment]
can you please create a PR ?

**Comment by dAverk** [comment]
Ok, I'll create PR with updated README
